#! /bin/sh

# autostart
sxhkd &
~/.fehbg &
ulauncher --hide-window --hide-window &
discord &
pcloud &
unclutter &
cbatticon &
compton &
dunst &
~/.config/polybar/launch.sh &

if [[ $(hostname) == 'cat-laptop' ]]; then
  bspc monitor -d term code web social office games steam VIII cloud music
elif [[ $(hostname) == 'cat-desktop' ]]; then
  xset -dpms s off
  bspc monitor DVI-I-0 -d web social cloud music
  bspc monitor DVI-D-0 -d term code office games steam VIII
fi

bspc config border_width         2
bspc config normal_border_color	 \#383c4a
bspc config active_border_color  \#d2d2d2
bspc config window_gap           10

#bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# code
bspc rule -a Atom desktop='code' follow=on
bspc rule -a Godot desktop='code' follow=on

# web
bspc rule -a Firefox desktop='web' follow=on

# social
bspc rule -a discord desktop='social'

# office
bspc rule -a libreoffice desktop='office' state=tiled follow=on
bspc rule -a Soffice desktop='office' state=tiled follow=on

# steam
bspc rule -a Steam desktop='steam'

# game
bspc rule -a ffxiv_dx11.exe desktop='games' state=fullscreen follow=on

# cloud
bspc rule -a ownCloud desktop='cloud' state=tiled
bspc rule -a pcloud desktop='cloud' state=pseudo_tiled

# music
bspc rule -a URxvt:Music desktop='music' follow=on

# misc
bspc rule -a Ulauncher state=floating
bspc rule -a Ulauncher border=off
